### PR TITLE
fix(firestore): support unlimited number of where conditions

### LINKED ISSUE #1313: bug: Firestore get ignores any where conditions beyond the first two
### Bug Description

If you make a `get` `callFirestore` with more than two where conditions, any additional where conditions are silently dropped. For example: this call will return projects where `bar` does not equal `def`:

```ts
cy.callFirestore("get", "projects", {
    where: [
        ["active", "==", true],
        ["foo", "==", "abc"],
        ["bar", "==", "def"],
    ],
})
```

As another example showing that the where order matters, this call will return projects that aren't active:

```ts
cy.callFirestore("get", "projects", {
    where: [
        ["name", ">=", "abc"],
        ["name", "<=", "abc\xff"], 
        ["active", "==", true],
    ],
})
```

Originally reported here: https://github.com/prescottprue/cypress-firebase/issues/501#issuecomment-1729915139

### Why It Happens

This happens because the `where` option handling only destructures two where conditions out of the array: https://github.com/prescottprue/cypress-firebase/blob/885abba7068fe4a392c47dcac828d8f93e53c17a/src/firebase-utils.ts#L276-L283

### Solution

Opened this just to track the issue for the fix in PR: #1314

### PR DESCRIPTION
**Pull request by dominics**
### Description

Fixes #1313

Adds a failing test first, where we have two documents that match the first two where conditions. If we are processing all three where conditions correctly, the query should uniquely identify a single document instead, to pass.

Verified the fix in a Cypress project of mine

### CODE REVIEW

File: src/firebase-utils.ts [hunk 1]
```diff
@@ -274,12 +274,13 @@ export function slashPathToFirestoreRef(
     typeof ref.where === 'function'
   ) {
     if (Array.isArray(options.where[0])) {
-      const [where1, where2] = options.where as WhereOptions[];
-      ref = applyWhere(
-        applyWhere(ref, where1, options.statics || firestoreStatics),
-        where2,
-        options.statics || firestoreStatics,
-      );
+      (options.where as WhereOptions[]).forEach((whereCondition) => {
```
Comment (prescottprue) [inline src/firebase-utils.ts:277]: Great catch!
